name: sayurinaja
description: Aplikasi untuk mempermudah petani berkomunikasi dan bertransaksi dalam skala luas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

#================== DEPENDENCIES ==================#
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1

#================ DEV DEPENDENCIES ================#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

#============= FLUTTER LAUNCHER ICONS ==============#
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

#================= FLUTTER CONFIG ==================#
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png